#pragma once

// Auto-generated by dtgen from boards/pynq-z2.yaml -- DO NOT EDIT
// Board: PYNQ-Z2

#include <cstdint>

#include "hal/Uart.h"

namespace board
{
    // Board identity
    constexpr const char *kBoardName = "PYNQ-Z2";
    constexpr const char *kMcu = "Zynq-7020";
    constexpr const char *kArch = "cortex-a9";

    // Clocks (Hz)
    constexpr std::uint32_t kSystemClock = 650000000;
    constexpr std::uint32_t kApb1Clock = 100000000;
    constexpr std::uint32_t kApb2Clock = 100000000;

    // Memory regions
    constexpr std::uint32_t kDdrBase = 0x00100000;
    constexpr std::uint32_t kDdrSize = 0x1FF00000;

    // Console UART
    constexpr hal::UartId kConsoleUart = hal::UartId::Uart0;
    constexpr std::uint32_t kConsoleBaud = 115200;
    constexpr bool kHasConsoleTx = false;
    constexpr bool kHasConsoleRx = false;

    // LED
    constexpr bool kHasLed = false;

    // Features
    constexpr bool kHasFpu = true;

}  // namespace board
