#pragma once

// Auto-generated by dtgen from boards/stm32f207zgt6.yaml -- DO NOT EDIT
// Board: STM32F207ZGT6

#include <cstdint>

#include "hal/Gpio.h"
#include "hal/Uart.h"

namespace board
{
    // Board identity
    constexpr const char *kBoardName = "STM32F207ZGT6";
    constexpr const char *kMcu = "STM32F207ZGT6";
    constexpr const char *kArch = "cortex-m3";

    // Clocks (Hz)
    constexpr std::uint32_t kSystemClock = 120000000;
    constexpr std::uint32_t kApb1Clock = 30000000;
    constexpr std::uint32_t kApb2Clock = 60000000;
    constexpr std::uint32_t kHseClock = 25000000;

    // Memory regions
    constexpr std::uint32_t kFlashBase = 0x08000000;
    constexpr std::uint32_t kFlashSize = 0x00100000;
    constexpr std::uint32_t kSramBase = 0x20000000;
    constexpr std::uint32_t kSramSize = 0x00020000;

    // Console UART
    constexpr hal::UartId kConsoleUart = hal::UartId::Usart1;
    constexpr std::uint32_t kConsoleBaud = 115200;
    constexpr bool kHasConsoleTx = true;
    constexpr hal::Port kConsoleTxPort = hal::Port::A;
    constexpr std::uint8_t kConsoleTxPin = 9;
    constexpr std::uint8_t kConsoleTxAf = 7;

    // LED
    constexpr bool kHasLed = true;
    constexpr hal::Port kLedPort = hal::Port::C;
    constexpr std::uint8_t kLedPin = 13;

    // Features
    constexpr bool kHasFpu = false;

}  // namespace board
