#pragma once

// Auto-generated by dtgen from boards/stm32f407zgt6.yaml -- DO NOT EDIT
// Board: STM32F407ZGT6

#include <cstdint>

#include "hal/Gpio.h"
#include "hal/Uart.h"

namespace board
{
    // Board identity
    constexpr const char *kBoardName = "STM32F407ZGT6";
    constexpr const char *kMcu = "STM32F407ZGT6";
    constexpr const char *kArch = "cortex-m4";

    // Clocks (Hz)
    constexpr std::uint32_t kSystemClock = 168000000;
    constexpr std::uint32_t kApb1Clock = 42000000;
    constexpr std::uint32_t kApb2Clock = 84000000;
    constexpr std::uint32_t kHseClock = 8000000;

    // Memory regions
    constexpr std::uint32_t kFlashBase = 0x08000000;
    constexpr std::uint32_t kFlashSize = 0x00100000;
    constexpr std::uint32_t kSramBase = 0x20000000;
    constexpr std::uint32_t kSramSize = 0x00020000;
    constexpr std::uint32_t kCcmBase = 0x10000000;
    constexpr std::uint32_t kCcmSize = 0x00010000;

    // Console UART
    constexpr hal::UartId kConsoleUart = hal::UartId::Usart1;
    constexpr std::uint32_t kConsoleBaud = 115200;
    constexpr bool kHasConsoleTx = true;
    constexpr hal::Port kConsoleTxPort = hal::Port::A;
    constexpr std::uint8_t kConsoleTxPin = 9;
    constexpr std::uint8_t kConsoleTxAf = 7;

    // LED
    constexpr bool kHasLed = true;
    constexpr hal::Port kLedPort = hal::Port::C;
    constexpr std::uint8_t kLedPin = 13;

    // Features
    constexpr bool kHasFpu = true;

}  // namespace board
