"""
C++ constexpr header emitter for dtgen.

Generates a BoardConfig.h with constexpr constants from a BoardDescription.
"""

from .schema import BoardDescription
from typing import Optional


# Map YAML uart names to hal::UartId enum values
UART_ID_MAP = {
    "uart0": "Uart0",
    "usart1": "Usart1",
    "usart2": "Usart2",
    "usart3": "Usart3",
    "uart4": "Uart4",
    "uart5": "Uart5",
    "usart6": "Usart6",
}


def _cap_region(name: str) -> str:
    """Capitalize a memory region name for constant names.

    'flash' -> 'Flash', 'sram' -> 'Sram', 'ccm' -> 'Ccm', 'ddr' -> 'Ddr'
    """
    return name[0].upper() + name[1:]


def emit_board_config_h(
    bd: BoardDescription, source_path: Optional[str] = None
) -> str:
    """Generate a C++ BoardConfig.h header from a BoardDescription.

    Args:
        bd: Parsed board description.
        source_path: Optional path to the source YAML file (for comment).

    Returns:
        Complete C++ header file content as a string.
    """
    lines = []

    # Header guard and comment
    lines.append("#pragma once")
    lines.append("")
    source_note = ""
    if source_path:
        source_note = f" from {source_path}"
    lines.append(f"// Auto-generated by dtgen{source_note} -- DO NOT EDIT")
    lines.append(f"// Board: {bd.board_name}")
    lines.append("")

    # Includes
    lines.append("#include <cstdint>")
    lines.append("")

    needs_gpio = (
        bd.led is not None
        or bd.console_tx is not None
        or bd.console_rx is not None
    )
    if needs_gpio:
        lines.append('#include "hal/Gpio.h"')
    lines.append('#include "hal/Uart.h"')
    lines.append("")

    # Open namespace
    lines.append("namespace board")
    lines.append("{")

    # ---- Board identity ----
    lines.append("    // Board identity")
    lines.append(f'    constexpr const char *kBoardName = "{bd.board_name}";')
    lines.append(f'    constexpr const char *kMcu = "{bd.mcu}";')
    lines.append(f'    constexpr const char *kArch = "{bd.arch}";')
    lines.append("")

    # ---- Clocks ----
    lines.append("    // Clocks (Hz)")
    lines.append(
        f"    constexpr std::uint32_t kSystemClock = {bd.clocks['system']};"
    )
    lines.append(
        f"    constexpr std::uint32_t kApb1Clock = {bd.clocks['apb1']};"
    )
    lines.append(
        f"    constexpr std::uint32_t kApb2Clock = {bd.clocks['apb2']};"
    )
    if "hse" in bd.clocks:
        lines.append(
            f"    constexpr std::uint32_t kHseClock = {bd.clocks['hse']};"
        )
    lines.append("")

    # ---- Memory regions ----
    lines.append("    // Memory regions")
    for region_name, region in bd.memory.items():
        cap = _cap_region(region_name)
        lines.append(
            f"    constexpr std::uint32_t k{cap}Base = "
            f"0x{region['base']:08X};"
        )
        lines.append(
            f"    constexpr std::uint32_t k{cap}Size = "
            f"0x{region['size']:08X};"
        )
    lines.append("")

    # ---- Console UART ----
    lines.append("    // Console UART")
    uart_enum = UART_ID_MAP.get(bd.console_uart, bd.console_uart)
    lines.append(
        f"    constexpr hal::UartId kConsoleUart = hal::UartId::{uart_enum};"
    )
    lines.append(
        f"    constexpr std::uint32_t kConsoleBaud = {bd.console_baud};"
    )

    has_tx = bd.console_tx is not None
    lines.append(
        f"    constexpr bool kHasConsoleTx = {'true' if has_tx else 'false'};"
    )
    if has_tx:
        port = bd.console_tx["port"]
        pin = bd.console_tx["pin"]
        af = bd.console_tx["af"]
        lines.append(
            f"    constexpr hal::Port kConsoleTxPort = hal::Port::{port};"
        )
        lines.append(f"    constexpr std::uint8_t kConsoleTxPin = {pin};")
        lines.append(f"    constexpr std::uint8_t kConsoleTxAf = {af};")

    has_rx = bd.console_rx is not None
    lines.append(
        f"    constexpr bool kHasConsoleRx = {'true' if has_rx else 'false'};"
    )
    if has_rx:
        port = bd.console_rx["port"]
        pin = bd.console_rx["pin"]
        af = bd.console_rx["af"]
        lines.append(
            f"    constexpr hal::Port kConsoleRxPort = hal::Port::{port};"
        )
        lines.append(f"    constexpr std::uint8_t kConsoleRxPin = {pin};")
        lines.append(f"    constexpr std::uint8_t kConsoleRxAf = {af};")
    lines.append("")

    # ---- LED ----
    lines.append("    // LED")
    has_led = bd.led is not None
    lines.append(
        f"    constexpr bool kHasLed = {'true' if has_led else 'false'};"
    )
    if has_led:
        port = bd.led["port"]
        pin = bd.led["pin"]
        lines.append(f"    constexpr hal::Port kLedPort = hal::Port::{port};")
        lines.append(f"    constexpr std::uint8_t kLedPin = {pin};")
    lines.append("")

    # ---- Features ----
    lines.append("    // Features")
    has_fpu = bd.features.get("fpu", False)
    lines.append(
        f"    constexpr bool kHasFpu = {'true' if has_fpu else 'false'};"
    )

    # Close namespace
    lines.append("")
    lines.append("}  // namespace board")
    lines.append("")

    return "\n".join(lines)
